// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2515;

import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc.team2515.commands.*;
import org.usfirst.frc.team2515.subsystems.*;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the TimedRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the build.properties file in 
 * the project.
 */
public class Robot extends TimedRobot {

    Command autonomousCommand;
    SendableChooser<Command> chooser = new SendableChooser<>();
    Command selectGyro;
    SendableChooser<Command> gyroChooser = new SendableChooser<>();

    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static driveSystem driveSystem;
    public static climbSystem climbSystem;
    public static clawSystem clawSystem;
    public static sonarSystem sonarSystem;
    public static liftSystem liftSystem;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public boolean driveWithGyro = false;

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    @Override
    public void robotInit() {
        RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSystem = new driveSystem();
        SmartDashboard.putData(driveSystem);
        climbSystem = new climbSystem();
        clawSystem = new clawSystem();
        SmartDashboard.putData(clawSystem);
        sonarSystem = new sonarSystem();
        SmartDashboard.putData(sonarSystem);
        liftSystem = new liftSystem();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();

        // Add commands to Autonomous Sendable Chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

        chooser.addObject("autoDriveForward: Default", new autoDriveForward(15));
        chooser.addDefault("autoStation1Left", new autoStation1Left());
        chooser.addObject("autoStation1Left", new autoStation1Left());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        
        RobotMap.liftSystemliftEncoder.reset();

        gyroChooser.addObject("Drive without Gyro", setGyroFalse());
        gyroChooser.addObject("Drive with Gyro", setGyroTrue());
        gyroChooser.addDefault("Drive without Gyro", setGyroFalse());
        
        SmartDashboard.putData("Auto mode", chooser);
		CameraServer.getInstance().startAutomaticCapture();

    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    @Override
    public void disabledInit(){

    }

    @Override
    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void autonomousInit() {
		String gameData;
		/**
		 * The following code pulls game data instructing the computer
		 * which side of the switch is the current alliance color.
		 * More information available at this URL:
		 * https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/826278-2018-game-data-details
		 */
		gameData = DriverStation.getInstance().getGameSpecificMessage();
		/*if(gameData.charAt(0) == 'L')
		{
			//Put left auto code here
			autonomousCommand = new autoDriveForward(15);
		} else {
			//Put right auto code here
		}*/
        //autonomousCommand = chooser.getSelected();
        // schedule the autonomous command (example)
		autonomousCommand = new autoDriveForward(20);
        if (autonomousCommand != null) autonomousCommand.start();
    }

    /**
     * This function is called periodically during autonomous
     */
    @Override
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
    		RobotMap.liftSystemliftEncoder.reset();
        if (autonomousCommand != null) autonomousCommand.cancel();
        selectGyro = gyroChooser.getSelected();
        if (selectGyro != null) selectGyro.start();
    }

    /**
     * This function is called periodically during operator control
     */
    @Override
    public void teleopPeriodic() {
        Scheduler.getInstance().run();

        if (driveWithGyro == true) {
        		// Pass gyro value to drive command
        		Robot.driveSystem.drive(Robot.oi.joystick.getX()*Robot.oi.getAccelerateMultiplier(), Robot.oi.joystick.getY()*Robot.oi.getAccelerateMultiplier(),(Robot.oi.joystick.getZ()*0.75),RobotMap.driveSystemanalogGyro.getAngle());
        } else {
        		// Set gyro value to static 0.0
        		Robot.driveSystem.drive(Robot.oi.joystick.getX()*Robot.oi.getAccelerateMultiplier(), Robot.oi.joystick.getY()*Robot.oi.getAccelerateMultiplier(),(Robot.oi.joystick.getZ()*0.75),0.0);
        }
    }
    
    // Set the drive with gyro boolean to true
    public Command setGyroTrue() {
    		driveWithGyro = true;
    		return null;
    }
    // Set the drive with gyro boolean to false
    public Command setGyroFalse() {
		driveWithGyro = false;
		return null;
}
}
