// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2515;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.PWMTalonSRX;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.drive.MecanumDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSystemleftFrontMotor;
    public static SpeedController driveSystemleftRearMotor;
    public static SpeedController driveSystemrightFrontMotor;
    public static SpeedController driveSystemrightRearMotor;
    public static MecanumDrive driveSystemmecanumDrive;
    public static AnalogGyro driveSystemanalogGyro;
    public static WPI_TalonSRX climbSystemclimbMotor;
    public static DigitalInput clawSystemclawLimit;
    public static SpeedController clawSystemclawMotor;
    public static AnalogInput sonarSystemfrontSonar;
    public static WPI_TalonSRX liftSystemliftMotor;
    public static Encoder liftSystemliftEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSystemleftFrontMotor = new Talon(0);
        LiveWindow.addActuator("driveSystem", "leftFrontMotor", (Talon) driveSystemleftFrontMotor);
        driveSystemleftFrontMotor.setInverted(false);
        driveSystemleftRearMotor = new Talon(1);
        LiveWindow.addActuator("driveSystem", "leftRearMotor", (Talon) driveSystemleftRearMotor);
        driveSystemleftRearMotor.setInverted(false);
        driveSystemrightFrontMotor = new Talon(2);
        LiveWindow.addActuator("driveSystem", "rightFrontMotor", (Talon) driveSystemrightFrontMotor);
        driveSystemrightFrontMotor.setInverted(false);
        driveSystemrightRearMotor = new Talon(3);
        LiveWindow.addActuator("driveSystem", "rightRearMotor", (Talon) driveSystemrightRearMotor);
        driveSystemrightRearMotor.setInverted(false);
        driveSystemmecanumDrive = new MecanumDrive(driveSystemleftFrontMotor, driveSystemleftRearMotor,
              driveSystemrightFrontMotor, driveSystemrightRearMotor);
        LiveWindow.addActuator("driveSystem", "mecanumDrive", driveSystemmecanumDrive);
        driveSystemmecanumDrive.setSafetyEnabled(true);
        driveSystemmecanumDrive.setExpiration(0.1);
        driveSystemmecanumDrive.setMaxOutput(1.0);

        driveSystemanalogGyro = new AnalogGyro(0);
        LiveWindow.addSensor("driveSystem", "analogGyro", driveSystemanalogGyro);
        driveSystemanalogGyro.setSensitivity(0.007);
        climbSystemclimbMotor = new WPI_TalonSRX(2);
        
        
        clawSystemclawLimit = new DigitalInput(0);
        LiveWindow.addSensor("clawSystem", "clawLimit", clawSystemclawLimit);
        
        clawSystemclawMotor = new PWMTalonSRX(4);
        LiveWindow.addActuator("clawSystem", "clawMotor", (PWMTalonSRX) clawSystemclawMotor);
        clawSystemclawMotor.setInverted(false);
        sonarSystemfrontSonar = new AnalogInput(1);
        LiveWindow.addSensor("sonarSystem", "frontSonar", sonarSystemfrontSonar);
        
        liftSystemliftMotor = new WPI_TalonSRX(1);
        
        
        liftSystemliftEncoder = new Encoder(1, 2, true, EncodingType.k4X);
        LiveWindow.addSensor("liftSystem", "liftEncoder", liftSystemliftEncoder);
        liftSystemliftEncoder.setDistancePerPulse(1.0);
        liftSystemliftEncoder.setPIDSourceType(PIDSourceType.kRate);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
